name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  sonar-check:
    name: Sonar Check
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Cache SonarScanner to speed up builds
      - name: Cache SonarScanner
        uses: actions/cache@v3
        with:
          path: ~\.dotnet\tools
          key: ${{ runner.os }}-sonar-scanner-5.15.0
          restore-keys: ${{ runner.os }}-sonar-scanner-

      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner --version 5.15.0
        shell: pwsh

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin `
            /k:"ppanchen_NetSdrClient" `
            /o:"ppanchen" `
            /d:sonar.token="$env:SONAR_TOKEN" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.exclusions="**/bin/**,**/obj/**,**/.github/**"
          
          dotnet restore NetSdrClient.sln
          dotnet build NetSdrClient.sln -c Release --no-restore
          
          dotnet sonarscanner end /d:sonar.token="$env:SONAR_TOKEN"
        shell: pwsh
